import { chmod, mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { paths } from './paths';
import type { AppConfig, AppPreferences, TenantBrand } from './schema';
import { secretKeyForApp } from './schema';

export async function loadConfig(path: string = paths.configFile): Promise<Partial<AppConfig>> {
  try {
    const text = await readFile(path, 'utf8');
    return JSON.parse(text) as Partial<AppConfig>;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return {};
    throw err;
  }
}

/**
 * Atomic write: write to a sibling temp file with 0600 perms, then rename
 * (atomic on POSIX) into place. Avoids the partial-write window where a
 * crash could leave the config truncated, and keeps secret-bearing bytes
 * from ever existing at the final path with looser perms.
 */
/**
 * Build an AppConfig that points the app's secret at the encrypted local
 * keystore via an exec-provider SecretRef. Used by /account change and the
 * first-run migration path. Preserves the existing `preferences` block so
 * users don't lose unrelated settings on credential update.
 *
 * The provider command is a thin shell wrapper bridge writes under
 * `~/.lark-channel/secrets-getter` (always user-owned, never a symlink) so
 * lark-cli's AssertSecurePath audit accepts it regardless of how node was
 * installed (Homebrew / Volta / system pkg may put node behind a symlink
 * or root-own it). The wrapper internally `exec`s the real node + bridge
 * with `secrets get`. Bridge itself short-circuits the spawn and reads the
 * keystore directly when it sees its own wrapper path in `command`.
 */
export async function buildEncryptedAccountConfig(
  appId: string,
  tenant: TenantBrand,
  preferences?: AppPreferences,
): Promise<AppConfig> {
  const wrapperPath = await ensureSecretsGetterWrapper();
  return {
    accounts: {
      app: {
        id: appId,
        secret: {
          source: 'exec',
          provider: 'bridge',
          id: secretKeyForApp(appId),
        },
        tenant,
      },
    },
    secrets: {
      providers: {
        bridge: {
          source: 'exec',
          command: wrapperPath,
          // The wrapper has args baked in; pass none here.
          args: [],
        },
      },
    },
    ...(preferences ? { preferences } : {}),
  };
}

/**
 * Write (or rewrite) the secrets-getter wrapper to point at the currently-
 * running node + bridge entry script. Always rewrites — node path can move
 * between bridge runs (nvm version switch, re-install) and the wrapper
 * must stay in sync. Returns the wrapper path.
 *
 * - Unix: a shell script with perms 0o700.
 * - Windows: a .cmd batch file with perms 0o444 (read-only).
 *
 * Windows cannot execute `#!/bin/sh` scripts directly; lark-cli also
 * rejects mode 0o666 files as "world-writable (mode 0666)". fs.chmod(0o700)
 * on Windows leaves the file writable because Windows only maps the
 * write-bit — Node still reports mode 0o666. 0o444 (read-only) produces
 * mode 0o444, which passes the audit. The .cmd wrapper is what lark-cli
 * actually runs at exec time.
 */
export async function ensureSecretsGetterWrapper(): Promise<string> {
  const wrapperPath = paths.secretsGetterScript;
  const node = process.execPath;
  const bridgeEntry = process.argv[1] ?? '';
  const isWin = process.platform === 'win32';

  let content: string;
  let mode: number;

  if (isWin) {
    // .cmd batch file: paths use double quotes (cmd doesn't understand single
    // quotes), REM for comments.
    content =
      `@echo off\r\n` +
      `REM Auto-generated by lark-channel-bridge. Do not edit.\r\n` +
      `REM Forwards exec-provider requests to: node bridge secrets get\r\n` +
      `"${node}" "${bridgeEntry}" secrets get %*\r\n`;
    // Node reports 0o444 for read-only files on Windows — no world-writable
    // bits, passes lark-cli's AssertSecurePath audit.
    mode = 0o444;
  } else {
    const sq = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`;
    content =
      `#!/bin/sh\n` +
      `# Auto-generated by lark-channel-bridge. Do not edit.\n` +
      `# Forwards exec-provider requests to: node bridge secrets get\n` +
      `exec ${sq(node)} ${sq(bridgeEntry)} secrets get "$@"\n`;
    mode = 0o700;
  }

  await mkdir(dirname(wrapperPath), { recursive: true });
  const tmp = `${wrapperPath}.tmp-${process.pid}`;
  await writeFile(tmp, content, 'utf8');
  // Windows: skip chmod entirely. lark-cli's Go binary doesn't respect the
  // DOS read-only attribute for its world-writable audit anyway, and a
  // read-only target breaks rename() on the next run.
  if (!isWin) await chmod(tmp, mode);
  await rename(tmp, wrapperPath);
  if (!isWin) await chmod(wrapperPath, mode);
  return wrapperPath;
}

export async function saveConfig(cfg: AppConfig, path: string = paths.configFile): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  const tmp = `${path}.tmp-${process.pid}`;
  await writeFile(tmp, `${JSON.stringify(cfg, null, 2)}\n`, 'utf8');
  // chmod the temp file before rename, so the destination path is never
  // visible with default permissions.
  await chmod(tmp, 0o600);
  await rename(tmp, path);
}
